{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "22ba1f53",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os \n",
    "import csv\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c107c218",
   "metadata": {},
   "outputs": [],
   "source": [
    "cache_misses = pd.read_csv(\"../ce_data/caches/l1d_miss_ratio.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e4d00533",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n",
      "<ipython-input-3-ff3ff2ea8081>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.\n",
      "  reuse_distances = reuse_distances.append(x, ignore_index=True)\n"
     ]
    }
   ],
   "source": [
    "reuse_distances = pd.DataFrame()\n",
    "for file in os.listdir(\"../ce_data/reuse_distances\"):\n",
    "    x = pd.read_csv(\"../ce_data/reuse_distances/\"+file)\n",
    "    reuse_distances = reuse_distances.append(x, ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "4560ce8a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                         id        32        64       128       256       512  \\\n",
      "0       400.perlbench-41B_0  0.001166  0.001166  0.001166  0.001166  0.001166   \n",
      "1       400.perlbench-41B_1  0.001646  0.001646  0.001646  0.001646  0.001646   \n",
      "2       400.perlbench-41B_2  0.001015  0.001015  0.001015  0.001015  0.001015   \n",
      "3       400.perlbench-41B_3  0.000598  0.000598  0.000598  0.000598  0.000598   \n",
      "4       400.perlbench-41B_4  0.001044  0.001044  0.001044  0.001044  0.001044   \n",
      "...                     ...       ...       ...       ...       ...       ...   \n",
      "141556     657.xz_s-56B_744  0.005654  0.005654  0.005654  0.005654  0.005654   \n",
      "141557     657.xz_s-56B_745  0.005642  0.005642  0.005642  0.005642  0.005642   \n",
      "141558     657.xz_s-56B_746  0.005655  0.005655  0.005655  0.005655  0.005655   \n",
      "141559     657.xz_s-56B_747  0.005641  0.005641  0.005641  0.005641  0.005641   \n",
      "141560     657.xz_s-56B_748  0.005643  0.005643  0.005643  0.005643  0.005643   \n",
      "\n",
      "            1024      2048      4096      8192  \n",
      "0       0.001166  0.001166  0.001166  0.001166  \n",
      "1       0.001646  0.001646  0.001646  0.001646  \n",
      "2       0.001015  0.001015  0.001015  0.001015  \n",
      "3       0.000598  0.000598  0.000598  0.000598  \n",
      "4       0.001044  0.001044  0.001044  0.001044  \n",
      "...          ...       ...       ...       ...  \n",
      "141556  0.005654  0.005654  0.005654  0.005654  \n",
      "141557  0.005642  0.005642  0.005642  0.005642  \n",
      "141558  0.005655  0.005655  0.005655  0.005655  \n",
      "141559  0.005641  0.005641  0.005641  0.005641  \n",
      "141560  0.005643  0.005643  0.005643  0.005643  \n",
      "\n",
      "[141561 rows x 10 columns]\n",
      "                         id       0      1      2      3     4     5      6  \\\n",
      "0       400.perlbench-41B_0  105856  45136  24544  15840  4704  9104  20144   \n",
      "1       400.perlbench-41B_1   94192  48656  27200  16912  5280  8448  17264   \n",
      "2       400.perlbench-41B_2   93200  39568  26640  18928  5552  8704  16096   \n",
      "3       400.perlbench-41B_3   86576  38368  26432  18320  5296  9648  15936   \n",
      "4       400.perlbench-41B_4  104944  42128  25744  16528  6368  8432  17712   \n",
      "...                     ...     ...    ...    ...    ...   ...   ...    ...   \n",
      "141556     657.xz_s-56B_744   47552  55344  10576   1776  4848   992   2192   \n",
      "141557     657.xz_s-56B_745   47600  54848  10544   1760  4912  1008   2192   \n",
      "141558     657.xz_s-56B_746   47584  55312  10432   1792  4816   960   2208   \n",
      "141559     657.xz_s-56B_747   47696  55264  10384   1760  4880  1008   2192   \n",
      "141560     657.xz_s-56B_748   47616  55296  10432   1776  4832   992   2192   \n",
      "\n",
      "           7      8  ...  3623878656  3690987520  3758096384  3825205248  \\\n",
      "0       6368   7968  ...           0           0           0           0   \n",
      "1       3840   2960  ...           0           0           0           0   \n",
      "2       3904   7200  ...           0           0           0           0   \n",
      "3       3760  10336  ...           0           0           0           0   \n",
      "4       5376   7264  ...           0           0           0           0   \n",
      "...      ...    ...  ...         ...         ...         ...         ...   \n",
      "141556  2160    368  ...           0           0           0           0   \n",
      "141557  2128    368  ...           0           0           0           0   \n",
      "141558  2144    368  ...           0           0           0           0   \n",
      "141559  2160    352  ...           0           0           0           0   \n",
      "141560  2144    368  ...           0           0           0           0   \n",
      "\n",
      "        3892314112  3959422976  4026531840  4093640704  4160749568  4227858432  \n",
      "0                0           0           0           0           0           0  \n",
      "1                0           0           0           0           0           0  \n",
      "2                0           0           0           0           0           0  \n",
      "3                0           0           0           0           0           0  \n",
      "4                0           0           0           0           0           0  \n",
      "...            ...         ...         ...         ...         ...         ...  \n",
      "141556           0           0           0           0           0           0  \n",
      "141557           0           0           0           0           0           0  \n",
      "141558           0           0           0           0           0           0  \n",
      "141559           0           0           0           0           0           0  \n",
      "141560           0           0           0           0           0           0  \n",
      "\n",
      "[141561 rows x 897 columns]\n"
     ]
    }
   ],
   "source": [
    "print(cache_misses)\n",
    "print(reuse_distances)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b560f234",
   "metadata": {},
   "outputs": [],
   "source": [
    "cache_misses = cache_misses.sort_values(\"id\", ascending=True, ignore_index=True)\n",
    "reuse_distances = reuse_distances.sort_values(\"id\", ascending=True, ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8c04f263",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Quick check if all columns are the same\n",
    "for i,j in zip(reuse_distances['id'], cache_misses['id']):\n",
    "    if i!=j:\n",
    "        print(i, j)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e860ea42",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(reuse_distances,cache_misses, test_size=0.3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "44869d49",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "78481        603.bwaves_s-2931B_625\n",
      "60935             481.wrf-1281B_338\n",
      "115610         641.leela_s-800B_336\n",
      "30999               445.gobmk-2B_36\n",
      "12465               429.mcf-22B_531\n",
      "                    ...            \n",
      "102414     623.xalancbmk_s-700B_594\n",
      "130973    649.fotonik3d_s-7084B_681\n",
      "129413    649.fotonik3d_s-1176B_625\n",
      "65965         482.sphinx3-1522B_146\n",
      "62242              481.wrf-455B_166\n",
      "Name: id, Length: 99092, dtype: object\n"
     ]
    }
   ],
   "source": [
    "X_train_ids = X_train[\"id\"]\n",
    "X_test_ids = X_test[\"id\"]\n",
    "y_train_ids = y_train[\"id\"]\n",
    "y_test_ids = y_test[\"id\"]\n",
    "\n",
    "print(X_train_ids)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "5a569df1",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train = X_train.drop(columns=[\"id\"])\n",
    "X_test = X_test.drop(columns=[\"id\"])\n",
    "y_train = y_train.drop(columns=[\"id\"])\n",
    "y_test = y_test.drop(columns=[\"id\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "3c537454",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(99092, 896) (42469, 896)\n",
      "(99092, 9) (42469, 9)\n"
     ]
    }
   ],
   "source": [
    "print(X_train.shape, X_test.shape)\n",
    "print(y_train.shape, y_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "6b1fbf9a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',\n",
      "       ...\n",
      "       '3623878656', '3690987520', '3758096384', '3825205248', '3892314112',\n",
      "       '3959422976', '4026531840', '4093640704', '4160749568', '4227858432'],\n",
      "      dtype='object', length=896)\n"
     ]
    }
   ],
   "source": [
    "print(X_train.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "id": "f228d088",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_10\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " dense_24 (Dense)            (None, 1024)              918528    \n",
      "                                                                 \n",
      " dense_25 (Dense)            (None, 1024)              1049600   \n",
      "                                                                 \n",
      " dense_26 (Dense)            (None, 9)                 9225      \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 1,977,353\n",
      "Trainable params: 1,977,353\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras import Input\n",
    "# Create the model\n",
    "model = Sequential()\n",
    "model.add(Input(shape=(896, )))\n",
    "# Add the input layer and the first hidden layer\n",
    "model.add(Dense(1024, activation='sigmoid'))\n",
    "\n",
    "# Add the second hidden layer\n",
    "model.add(Dense(1024, activation='sigmoid'))\n",
    "\n",
    "# Add the output layer\n",
    "model.add(Dense(9, activation='sigmoid'))\n",
    "\n",
    "# Compile the model\n",
    "model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\n",
    "# Print the model summary\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "id": "bae89238",
   "metadata": {},
   "outputs": [],
   "source": [
    "ll = model(X_train.to_numpy())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "id": "9b5c1d50",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tf.Tensor(\n",
      "[[0.28801483 0.6044907  0.45502704 ... 0.71171165 0.23265873 0.20295328]\n",
      " [0.33268002 0.5034498  0.46771303 ... 0.73570794 0.23044915 0.26496053]\n",
      " [0.28893918 0.59640616 0.47816816 ... 0.7349159  0.21950576 0.21934134]\n",
      " ...\n",
      " [0.29208088 0.5345501  0.51180005 ... 0.73828024 0.21859095 0.24050203]\n",
      " [0.31866792 0.55891204 0.44222066 ... 0.7376148  0.20373449 0.24402003]\n",
      " [0.2816464  0.58128816 0.46634847 ... 0.7281808  0.22827178 0.24496563]], shape=(99092, 9), dtype=float32)\n"
     ]
    }
   ],
   "source": [
    "print(ll)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "id": "1a21d4d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/25\n",
      "3097/3097 [==============================] - 33s 10ms/step - loss: 1.7041 - accuracy: 0.0567\n",
      "Epoch 2/25\n",
      "3097/3097 [==============================] - 31s 10ms/step - loss: 1.6992 - accuracy: 0.0572\n",
      "Epoch 3/25\n",
      "3097/3097 [==============================] - 31s 10ms/step - loss: 1.6978 - accuracy: 0.0607\n",
      "Epoch 4/25\n",
      "3097/3097 [==============================] - 30s 10ms/step - loss: 1.6971 - accuracy: 0.0624\n",
      "Epoch 5/25\n",
      "3097/3097 [==============================] - 31s 10ms/step - loss: 1.6967 - accuracy: 0.0635\n",
      "Epoch 6/25\n",
      "3097/3097 [==============================] - 31s 10ms/step - loss: 1.6965 - accuracy: 0.0630\n",
      "Epoch 7/25\n",
      "3097/3097 [==============================] - 30s 10ms/step - loss: 1.6964 - accuracy: 0.0641\n",
      "Epoch 8/25\n",
      "3097/3097 [==============================] - 29s 9ms/step - loss: 1.6962 - accuracy: 0.0634\n",
      "Epoch 9/25\n",
      "3097/3097 [==============================] - 31s 10ms/step - loss: 1.6961 - accuracy: 0.0634\n",
      "Epoch 10/25\n",
      "3097/3097 [==============================] - 32s 10ms/step - loss: 1.6960 - accuracy: 0.0639\n",
      "Epoch 11/25\n",
      "3097/3097 [==============================] - 33s 11ms/step - loss: 1.6959 - accuracy: 0.0633\n",
      "Epoch 12/25\n",
      "3097/3097 [==============================] - 33s 11ms/step - loss: 1.6958 - accuracy: 0.0646\n",
      "Epoch 13/25\n",
      "3097/3097 [==============================] - 37s 12ms/step - loss: 1.6958 - accuracy: 0.0653\n",
      "Epoch 14/25\n",
      "3097/3097 [==============================] - 32s 10ms/step - loss: 1.6957 - accuracy: 0.0658\n",
      "Epoch 15/25\n",
      "3097/3097 [==============================] - 32s 10ms/step - loss: 1.6957 - accuracy: 0.0655\n",
      "Epoch 16/25\n",
      "3097/3097 [==============================] - 33s 11ms/step - loss: 1.6956 - accuracy: 0.0663\n",
      "Epoch 17/25\n",
      "3097/3097 [==============================] - 33s 11ms/step - loss: 1.6956 - accuracy: 0.0667\n",
      "Epoch 18/25\n",
      "3097/3097 [==============================] - 32s 10ms/step - loss: 1.6955 - accuracy: 0.0684\n",
      "Epoch 19/25\n",
      "3097/3097 [==============================] - 32s 10ms/step - loss: 1.6955 - accuracy: 0.0684\n",
      "Epoch 20/25\n",
      "3097/3097 [==============================] - 32s 10ms/step - loss: 1.6955 - accuracy: 0.0683\n",
      "Epoch 21/25\n",
      "3097/3097 [==============================] - 33s 10ms/step - loss: 1.6954 - accuracy: 0.0676\n",
      "Epoch 22/25\n",
      "3097/3097 [==============================] - 31s 10ms/step - loss: 1.6954 - accuracy: 0.0686\n",
      "Epoch 23/25\n",
      "3097/3097 [==============================] - 2261s 730ms/step - loss: 1.6954 - accuracy: 0.0679\n",
      "Epoch 24/25\n",
      "3097/3097 [==============================] - 34s 11ms/step - loss: 1.6953 - accuracy: 0.0687\n",
      "Epoch 25/25\n",
      "3097/3097 [==============================] - 32s 10ms/step - loss: 1.6953 - accuracy: 0.0685\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<keras.callbacks.History at 0x241cc343fa0>"
      ]
     },
     "execution_count": 107,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model.fit(X_train.to_numpy(), y_train.to_numpy(), epochs=25)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "f0bece96",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(9,), dtype=float32)\n",
      "tf.Tensor([9306. 9306. 9306. 9306. 9306. 9306. 9306. 9306. 9306.], shape=(9,), dtype=float32)\n",
      "tf.Tensor(\n",
      "[[0. 0. 0. ... 0. 0. 0.]\n",
      " [0. 0. 0. ... 0. 0. 0.]\n",
      " [0. 0. 0. ... 0. 0. 0.]\n",
      " ...\n",
      " [0. 0. 0. ... 0. 0. 0.]\n",
      " [1. 1. 1. ... 1. 1. 1.]\n",
      " [1. 1. 1. ... 1. 1. 1.]], shape=(42469, 9), dtype=float32)\n"
     ]
    }
   ],
   "source": [
    "f = model(X_test.to_numpy())\n",
    "print(f[0])\n",
    "print(sum(f))\n",
    "print(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3539e10d",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a431eed",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Local-venv",
   "language": "python",
   "name": "local-venv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
