#CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
#TOOL_ROOTS := champsim_tracer
#
#include $(CONFIG_ROOT)/makefile.config
#include $(TOOLS_ROOT)/Config/makefile.default.rules
#
# If the tool is built out of the kit, PIN_ROOT must be specified in the make invocation and point to the kit root.
#ifdef PIN_ROOT
#CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
#else
#CONFIG_ROOT := ../Config
#endif
#CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
#TOOLS_ROOT := $(PIN_ROOT)/source/tools
#include $(CONFIG_ROOT)/makefile.config
#include makefile.rules
#include $(TOOLS_ROOT)/Config/makefile.default.rules
#
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TOOL_ROOTS := champsim_tracer
TOOLS_ROOT := $(PIN_ROOT)/source/tools

include $(CONFIG_ROOT)/makefile.config
include $(TOOLS_ROOT)/Config/makefile.default.rules


